// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cart.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCarts = `-- name: CreateCarts :one
INSERT INTO carts (
 user_id, total_price 
) VALUES (
  $1, $2
)
RETURNING id, user_id, total_price
`

type CreateCartsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TotalPrice float64   `json:"total_price"`
}

func (q *Queries) CreateCarts(ctx context.Context, arg CreateCartsParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createCarts, arg.UserID, arg.TotalPrice)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.TotalPrice)
	return i, err
}

const getCarts = `-- name: GetCarts :one
SELECT id, user_id, total_price FROM carts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCarts(ctx context.Context, id uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCarts, id)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.TotalPrice)
	return i, err
}

const updateCarts = `-- name: UpdateCarts :one
UPDATE carts
  set total_price = $2
WHERE id = $1
RETURNING id, user_id, total_price
`

type UpdateCartsParams struct {
	ID         uuid.UUID `json:"id"`
	TotalPrice float64   `json:"total_price"`
}

func (q *Queries) UpdateCarts(ctx context.Context, arg UpdateCartsParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, updateCarts, arg.ID, arg.TotalPrice)
	var i Cart
	err := row.Scan(&i.ID, &i.UserID, &i.TotalPrice)
	return i, err
}
